### PR TITLE
install correctly chosen spool and copy archetype files

### PR DESCRIPTION
**Pull request by jaumard**
I just have one small bugs, 

After the npm install I tried to install archetype files to the project, but for some reason `readdir` is not giving me the newly install spools so archetype files are not installed.

Any idea @scott-wyatt ?

### CODE REVIEW

**Comment by jaumard** [comment]
Ok I figure it out :) path wasn't correct, now it's ok ! But I notice spools-router doesn't have his archetype files in the right place ;)

**Comment by jaumard** [comment]
fixed spool-router archetype https://github.com/fabrix-app/spool-router/pull/22

**Comment by jaumard** [comment]
I just notice something missing, index is not updated with new copied archetype :/

**Comment by jaumard** [comment]
Ok now index is also updated accordingly :) should be all good

**Comment by scott-wyatt** [comment]
Awesome! Ready to merge?

**Comment by jaumard** [comment]
Sure ! :)

**Pull request merged**
